(()=>{'use strict';
const accounts={student_demo:{p:'Demo@2026',role:'student',name:'سارة أحمد الخطيب',short:'سارة',label:'طالبة — الصف التاسع',avatar:'س'},team_demo:{p:'Team@2026',role:'student',name:'فريق المدار الأردني',short:'فريق المدار',label:'فريق — طالبان',avatar:'ف'},admin_demo:{p:'AdminDemo@2026',role:'admin',name:'مدير المسابقة التجريبي',short:'الإدارة',label:'إدارة المنصة',avatar:'إ'}};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];const demo=$('[data-demo]'),login=$('[data-login-screen]'),app=$('[data-app-screen]'),form=$('[data-login-form]'),msg=$('[data-login-msg]'),toast=$('[data-toast]');let files=[];
function openDemo(){demo.classList.add('open');demo.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}function closeDemo(){demo.classList.remove('open');demo.setAttribute('aria-hidden','true');document.body.style.overflow=''}function say(t){toast.textContent=t;toast.classList.add('show');clearTimeout(say.t);say.t=setTimeout(()=>toast.classList.remove('show'),2000)}
$$('[data-open-demo]').forEach(b=>b.onclick=openDemo);$$('[data-close-demo]').forEach(b=>b.onclick=closeDemo);
$$('[data-fill]').forEach(b=>b.onclick=()=>{form.username.value=b.dataset.fill;form.password.value=accounts[b.dataset.fill].p;msg.textContent='تم تعبئة الحساب التجريبي.'});
function setView(v){$$('[data-view-panel]').forEach(p=>p.classList.toggle('active',p.dataset.viewPanel===v));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v))}
form.onsubmit=e=>{e.preventDefault();const k=form.username.value.trim(),a=accounts[k];if(!a||form.password.value!==a.p){msg.textContent='بيانات الدخول التجريبية غير صحيحة.';return}msg.textContent='';login.hidden=true;app.hidden=false;$('[data-user-name]').textContent=a.name;$('[data-user-role]').textContent=a.label;$('[data-avatar]').textContent=a.avatar;if(a.role==='admin'){$('[data-student-nav]').hidden=true;$('[data-admin-nav]').hidden=false;$$('[data-role-panel="student"]').forEach(x=>x.classList.remove('active'));setView('admin-dashboard')}else{$('[data-student-nav]').hidden=false;$('[data-admin-nav]').hidden=true;$('[data-student-name]').textContent=a.short;$$('[data-role-panel="admin"]').forEach(x=>x.classList.remove('active'));setView('student-dashboard')}};
$$('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('[data-logout]').onclick=()=>{app.hidden=true;login.hidden=false;form.reset();msg.textContent=''};
const upload=$('[data-demo-upload]');upload.onchange=()=>{files=[...upload.files].slice(0,10);const box=$('[data-files]');box.innerHTML='';files.forEach(f=>{const d=document.createElement('div');d.textContent=`${f.name} — ${(f.size/1048576).toFixed(2)} MB — معاينة محلية فقط`;box.appendChild(d)});$('[data-review-files]').textContent=`${files.length} ملف`};
$('[data-submit-demo]').onclick=()=>{const ok=$('[data-pledge]').checked;const out=$('[data-submit-result]');if(!ok){out.textContent='وافق على التعهد أولًا.';out.style.color='#b05a4e';return}out.textContent='✓ تمت محاكاة الإرسال بنجاح — لم تُرسل أي بيانات أو ملفات إلى الإنترنت.';out.style.color='#18875a';say('تم الإرسال التجريبي بنجاح')};
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDemo()});
})();
